### ISSUE TITLE
Pulse OTLP support

### ISSUE THREAD

**Issue by dmeytin** [microsoft/pulse#10]
**Feature Request**
In addition to [pulse-prometheus](https://github.com/microsoft/pulse-prometheus) it would be great to have support for Open Telemetry Protocol (OTLP).
Is it planned already?

**Comment by microsoftielogan** [comment]
We plan to implement pulse-dotnet, which would implement the system diagnostics c# metrics lib. this lib follows open telemetry. let me know if this helps and close out the issue if so. thanks
